development:
  cloud_name: project-end
  api_key: '718283284198253'
  api_secret: KF3YLAoFPXVU3w6jByoDJCPgEco
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: project-end
  api_key: '718283284198253'
  api_secret: KF3YLAoFPXVU3w6jByoDJCPgEco
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: project-end
  api_key: '718283284198253'
  api_secret: KF3YLAoFPXVU3w6jByoDJCPgEco
  enhance_image_tag: true
  static_image_support: false
