default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Doanhnhan
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: project-end_development

test:
  <<: *default
  database: project-end_test
production:
  <<: *default
  database: project-end_production
  username: project-end
  password: <%= ENV['PROJECT-END_DATABASE_PASSWORD'] %>
