none: "none"
list_default_subject: ["Tiếng việt", "Ngữ văn", "Toán", "Đạo đức", "Tự nhiên và xã hội", "Lịch sử",
                      "Địa lý", "Giáo dục công dân", "Giáo dục kinh tế và pháp luật","Khoa học",
                      "Khoa học tự nhiên", "Vật lý", "Hóa Học", "Sinh học", "Công nghệ", "Tin học",
                      "Âm nhạc", "Mỹ thuật", "Giáo dục thể chất", "Hướng nghiệp", "Sinh hoạt lớp"]
